version: "3.8"
services:
  api:
    build: "./backend"
    ports:
      - "3001:3001"
    volumes:
      - "./backend:/app"
    links:
      - mongo
  mongo:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
