version: "3.8"
services:
  web:
    build: "./frontend"
    ports:
      - "3000:8080"
    volumes:
      - "./frontend:/home/app"
    depends_on:
      - api
  api:
    build: "./backend"
    ports:
      - "3001:3001"
    volumes:
      - "./backend:/home/app"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    volumes:
      - "./db:/data/db"
